apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostname
      version: 1.18.0
  template:
    metadata:
      labels:
        app: hostname
        version: 1.18.0
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80